Several map fixes
pinatacolada/topskylppc pull request #413
Opened 2022-09-19 10:30 UTC by becas22

- [x] Fixes #422
- [x] Fixes #420
- [x] Fixes #421
- [x] Fixes #425
- [x] Fixes #419
- [x] Fixes #417
- [x] Fixes #418
- [x] Fixes #431
- [x] Fixes #432
- [x] Fixes #433
- [x] Fixes #434
- [x] Fixes #435
- [x] Fixes #436
- [x] Fixes #437
- [x] Fixes #412

2022-09-19 11:59 UTC, becas22 commented
@pinatacolada vê se queres a shore toda no ground layout ou se queres cortada para ocupar menos espaço

2022-09-19 12:05 UTC, pinatacolada commented
Toda

2022-09-19 12:07 UTC, becas22 commented
ok, ficou só a shore de Portugal. Espanha e Marrocos não
Rivers estão todos, mesmo os que não aparecem

2022-09-23 18:27 UTC, pinatacolada requested changes

2022-09-23 18:27 UTC, pinatacolada commented on LPPC/Plugins/topsky/TopSkyMaps.txt
> +//SCTDATA:STAR\HOLDING LPPC VFA L 283.0 15000
why?

2022-09-23 18:27 UTC, pinatacolada commented on LPPC/Plugins/topsky/TopSkyMaps.txt
> +//SCTDATA:STAR\HOLDING LPPC SGR R 99.0 10000 14000
why?

2022-09-23 18:27 UTC, pinatacolada commented on LPPC/Plugins/topsky/TopSkyMaps.txt
> +COORD:N037.35.51.000:W007.57.31.000
tma de faro ta paralela à fir
![image](https://user-images.githubusercontent.com/13833056/192031427-695b8472-8df9-4f22-bef3-b8c20239de02.png)
e mesmo assim?

2022-09-23 18:27 UTC, pinatacolada commented on LPPC/Plugins/topsky/TopSkySettings.txt
> -Setup_LoadMap=ENVR\rivers
why?

2022-09-23 21:09 UTC, becas22 commented on LPPC/Plugins/topsky/TopSkyMaps.txt
> +COORD:N037.35.51.000:W007.57.31.000
é mm assim pelas coordenadas do AIP

2022-09-23 21:10 UTC, becas22 commented on LPPC/Plugins/topsky/TopSkySettings.txt
> -Setup_LoadMap=ENVR\rivers
não era suposto

2022-09-23 21:11 UTC, becas22 commented on LPPC/Plugins/topsky/TopSkyMaps.txt
> +//SCTDATA:STAR\HOLDING LPPC SGR R 99.0 10000 14000
hold em SGR não faz parte de nenhuma das STARs a Faro. A ideia com que fiquei é que apenas tinham os holds relevantes ao AD em si

2022-09-23 21:11 UTC, becas22 commented on LPPC/Plugins/topsky/TopSkyMaps.txt
> +//SCTDATA:STAR\HOLDING LPPC VFA L 283.0 15000
hold à vertical que suja o ecrã

2022-09-23 21:29 UTC, pinatacolada commented on LPPC/Plugins/topsky/TopSkyMaps.txt
> +//SCTDATA:STAR\HOLDING LPPC SGR R 99.0 10000 14000
no AIP aparece Faro como controlling unit

2022-09-23 21:36 UTC, becas22 commented on LPPC/Plugins/topsky/TopSkyMaps.txt
> +//SCTDATA:STAR\HOLDING LPPC SGR R 99.0 10000 14000
Percebo, mas como nao faz parte das stars acho que nao é relevante, idk

2022-09-25 00:23 UTC, pinatacolada commented on LPPC/Plugins/topsky/TopSkyMaps.txt
> +MAP:p_tma
tens a certeza deste? ha src de exister tma_nl de onde se deduz que existe tma

2022-09-25 00:40 UTC, pinatacolada requested changes

2022-09-25 00:40 UTC, pinatacolada commented on LPPC/Plugins/topsky/TopSkyMaps.txt
> +MAP:shore
o que esta no gng agora nao funciona com isto, liga as linhas desconectadas, esta a ligar marrocos a madeira ao continente

2022-09-25 23:01 UTC, becas22 commented on LPPC/Plugins/topsky/TopSkyMaps.txt
> +MAP:p_tma
95% de certeza que o mapa que dizia tma ligava e desligava as tmas

2022-09-25 23:01 UTC, becas22 commented on LPPC/Plugins/topsky/TopSkyMaps.txt
> +MAP:shore
o que está no GNG está ok, nao podes é fazer loadsct por limitaçao do topsky

2022-09-26 00:58 UTC, pinatacolada approved these changes

2022-09-26 01:19 UTC, merged