moves map definition to sct file
pinatacolada/topskylppc pull request #455
Opened 2022-09-30 20:50 UTC by becas22

loading sct data for:
ATZ
CTR
TMA
SHORE
BORDER

closes #427

2022-10-02 16:57 UTC, becas22 commented
AWYS marked as done due to GNG having data outside LPPC FIR. Pending confirmation how it is IRL

2022-10-07 02:31 UTC, pinatacolada requested changes
c35e31bea1e72ea23802ff6e51bb4eff5435ab65 este commit esta a mexer nas labels

2022-10-07 08:30 UTC, becas22 commented
São as mesmas mudanças do outro PR. Quando mexi nos settings mudei o ficheiro todo em vez de só a parte dos mapas

2022-10-07 17:30 UTC, pinatacolada commented
eu sei mas nao e assim que se faz isto, cada PR tem as alteracoes que precisam, se houver conflictos, que e o caso, esses conflictos resolvem se depois de o outro PR que os introduz estar merged

2022-10-13 18:46 UTC, becas22 commented
Qual é o conflito?

2022-10-13 20:54 UTC, pinatacolada commented
> Qual é o conflito?

uma linha em branco kekw
https://github.com/pinatacolada/topskylppc/pull/455/conflicts

2022-10-13 21:00 UTC, becas22 commented
> > Qual é o conflito?
> 
> uma linha em branco kekw https://github.com/pinatacolada/topskylppc/pull/455/conflicts

e suposto fazer o que?

2022-10-20 21:17 UTC, merged