Update TopSkyCPDLC ES IDs
pinatacolada/topskylppc pull request #487
Opened 2022-10-24 13:44 UTC by becas22

Falta rever os controller ID dos APP no GNG
Convem rever MADRID, SEVILLA e CANARIAS

fixes #486

2022-10-24 22:52 UTC, becas22 commented
@pinatacolada precisamos de decidir sector id dos apps em portugal

2022-10-25 02:02 UTC, pinatacolada commented
> @pinatacolada precisamos de decidir sector id dos apps em portugal

![image](https://user-images.githubusercontent.com/13833056/197664648-b8f43beb-d44d-4e0e-a8f5-750fa93675d5.png)

2022-10-25 13:05 UTC, pinatacolada commented
> confirmas que é para fazer LPPT_U_APP->LPPT_CTR?

oops nao

2022-10-25 13:06 UTC, becas22 commented
ok, isso não afeta este PR de qualquer das formas

2022-10-25 14:48 UTC, pinatacolada requested changes
falta actualizar todos os ACTIVE:ID do https://github.com/pinatacolada/topskylppc/blob/master/LPPC/Plugins/topsky/TopSkyMaps.txt

2022-10-25 14:48 UTC, pinatacolada commented on LPPC/Plugins/topsky/TopSkyCPDLC.txt
>  LOGIN:CMRM:MADRID CTL:LEM
Madrid nao estao actualizados no GNG

2022-10-25 14:48 UTC, pinatacolada commented on LPPC/Plugins/topsky/TopSkyCPDLC.txt
> +LOGIN:CSRA:SEVILLA CTL:SVL
nem estes

2022-10-25 14:48 UTC, pinatacolada commented on LPPC/Plugins/topsky/TopSkyCPDLC.txt
> +LOGIN:LPPO:SANTA MARIA OCA:SMARDR
falta actualizar gng

2022-10-25 14:48 UTC, pinatacolada commented on LPPC/Plugins/topsky/TopSkyCPDLC.txt
> +LOGIN:GMMM:CASABLANCA CTL:CAS
falta actualizar gng

2022-10-25 14:48 UTC, pinatacolada commented on LPPC/Plugins/topsky/TopSkyCPDLC.txt
> +LOGIN:GMMO:AGADIR CTL:AGA
falta actualizar gng

2022-10-25 14:48 UTC, pinatacolada commented on LPPC/Plugins/topsky/TopSkyCPDLC.txt
>  LOGIN:CCRA:CANARIAS CTL:GC
diferente do gng

2022-10-25 14:48 UTC, pinatacolada commented on LPPC/Plugins/topsky/TopSkyCPDLC.txt
> +LOGIN:EURW:EUROCONTROL CTL:EURO
diferente do gng

2022-10-25 14:58 UTC, pinatacolada requested changes

2022-10-25 14:58 UTC, pinatacolada commented on LPPC/Plugins/topsky/TopSkyCPDLC.txt
> +LOGIN:CMRC:MADRID CTL:LMEC
typo

2022-10-25 15:01 UTC, becas22 commented on LPPC/Plugins/topsky/TopSkyCPDLC.txt
> +LOGIN:CMRC:MADRID CTL:LMEC
typo onde?

2022-10-25 15:11 UTC, pinatacolada commented on LPPC/Plugins/topsky/TopSkyCPDLC.txt
> +LOGIN:CMRC:MADRID CTL:LMEC
LMEC/LEMC

2022-10-25 15:40 UTC, becas22 commented
> falta actualizar todos os ACTIVE:ID do https://github.com/pinatacolada/topskylppc/blob/master/LPPC/Plugins/topsky/TopSkyMaps.txt

isso pode ser noutro PR, nao?

2022-10-25 15:53 UTC, pinatacolada commented
> > falta actualizar todos os ACTIVE:ID do https://github.com/pinatacolada/topskylppc/blob/master/LPPC/Plugins/topsky/TopSkyMaps.txt
> 
> isso pode ser noutro PR, nao?

deve ser feito neste, senao os mapas deixam de funcionar

2022-10-27 21:46 UTC, becas22 commented
> > > falta actualizar todos os ACTIVE:ID do https://github.com/pinatacolada/topskylppc/blob/master/LPPC/Plugins/topsky/TopSkyMaps.txt
> > 
> > 
> > isso pode ser noutro PR, nao?
> 
> deve ser feito neste, senao os mapas deixam de funcionar

os mapas já deixam de funcionar pelo SCT file, não é por isto

2022-10-27 23:10 UTC, pinatacolada commented
> > > > falta actualizar todos os ACTIVE:ID do https://github.com/pinatacolada/topskylppc/blob/master/LPPC/Plugins/topsky/TopSkyMaps.txt
> > > 
> > > 
> > > isso pode ser noutro PR, nao?
> > 
> > 
> > deve ser feito neste, senao os mapas deixam de funcionar
> 
> os mapas já deixam de funcionar pelo SCT file, não é por isto

pelo sct que ainda nao fui published funciona, que e o que vai ser publicado com o release. doesnt matter, o que interessa e que alterando IDs num sitio tem de se alterar em todos, senao o pr fica a meio. cada pr deve ser o mais nuclear possivel em relacao as alteracoes, nao distribuir uma alteracao por varios pr nem por varias alteracoes nao relacionadas num pr

2022-11-01 16:53 UTC, becas22 commented
@pinatacolada acho que agora está pronto

2022-11-01 17:16 UTC, pinatacolada approved these changes

2022-11-01 17:16 UTC, merged