Adds comm type indicator to GR labels
pinatacolada/topskylppc pull request #601
Opened 2023-01-25 15:32 UTC by eusaylah

Adds comm type to labels in approach window

2023-01-25 18:08 UTC, pinatacolada requested changes

2023-01-25 18:08 UTC, pinatacolada commented on LPPC/Plugins/GroundRadar/GRpluginSettings.txt
> +Label=GND:OTH:2:WTC,0,0:ATYP,2,0
nao adicionar isto, nao faz parte do sistema real

2023-01-25 18:09 UTC, pinatacolada commented on LPPC/Plugins/GroundRadar/GRpluginSettings.txt
> +Label=APP:UNC:0:ALRT,0,0:COMM,0,1
fyi, uncorrelated nao sabe se tem voz ou nao, portanto isto nunca vai ser mostrado

2023-01-25 23:47 UTC, becas22 commented on LPPC/Plugins/GroundRadar/GRpluginSettings.txt
> +Label=APP:UNC:0:ALRT,0,0:COMM,0,1
Eu mantinha, para os casos que se desliga o pro mode

2023-01-26 00:23 UTC, pinatacolada commented on LPPC/Plugins/GroundRadar/GRpluginSettings.txt
> +Label=APP:UNC:0:ALRT,0,0:COMM,0,1
pro mode nao tem uncorrelateds

2023-01-26 00:23 UTC, becas22 commented on LPPC/Plugins/GroundRadar/GRpluginSettings.txt
> +Label=APP:UNC:0:ALRT,0,0:COMM,0,1
Hmm, true

2023-01-26 00:33 UTC, pinatacolada approved these changes

2023-01-26 00:34 UTC, merged