More maps updates
pinatacolada/topskylppc pull request #619
Opened 2023-02-18 00:41 UTC by becas22

2023-03-15 20:17 UTC, pinatacolada reviewed
falta COLOR: de ENR_MAP\lim ?

2023-03-15 21:12 UTC, pinatacolada requested changes

2023-03-16 13:53 UTC, becas22 commented on LPPC/Plugins/topsky/TopSkySettings.txt
> +Setup_LoadMap=TWRCAS\ext_cntrline_35
São fotos antigas. Onde vi usarem foi num app. Em Cascais até faz sentido usar se houver

2023-03-16 13:53 UTC, becas22 commented on LPPC/Plugins/topsky/TopSkyMaps.txt
> +FOLDER:APP
A source é que já não exista esse mapa

2023-03-17 00:04 UTC, pinatacolada commented on LPPC/Plugins/topsky/TopSkyMaps.txt
> +FOLDER:APP
se ja nao existe e para apagar

2023-03-17 00:05 UTC, pinatacolada commented on LPPC/Plugins/topsky/TopSkySettings.txt
> +Setup_LoadMap=TWRCAS\ext_cntrline_35
twrlis nao usa, ter ecl nas twr nao ajuda grande coisa

2023-03-17 09:55 UTC, becas22 commented on LPPC/Plugins/topsky/TopSkyMaps.txt
> +FOLDER:APP
Então eu não apaguei? Se calhar foi por não estar no sítio que esperava mas como não encontrei noutro sítio dei o meu best guess mas achava que tinha apagado

2023-03-17 09:56 UTC, becas22 commented on LPPC/Plugins/topsky/TopSkySettings.txt
> +Setup_LoadMap=TWRCAS\ext_cntrline_35
Então sugeres passar de lpcs twr para lis app?

2023-03-17 09:57 UTC, becas22 commented on LPPC/Plugins/topsky/TopSkyMaps.txt
> -COLOR:MAP_GREY
Recordo-me de ter testado e estar tudo ok
Mexi nisto para meter o shade da AIC, que pelo que percebi não está no mapa lim, deve estar no shade. Mas para não estar a criar uma folder só para um mapa, meti aqui para tudo

2023-03-17 11:01 UTC, becas22 commented on LPPC/Plugins/topsky/TopSkyMaps.txt
> +FOLDER:APP
ya tava a ver na minha branch, não tem lá isso

2023-03-17 11:02 UTC, becas22 commented on LPPC/Plugins/topsky/TopSkyMaps.txt
> -COLOR:MAP_GREY
![image](https://user-images.githubusercontent.com/11005754/225887296-62adfc39-8777-4d0a-a635-ddc8b8082328.png)

2023-03-17 11:03 UTC, becas22 commented on LPPC/Plugins/topsky/TopSkyMaps.txt
> -COLOR:MAP_GREY
a cor é antes ou depois?

2023-03-17 13:23 UTC, pinatacolada commented on LPPC/Plugins/topsky/TopSkySettings.txt
> +Setup_LoadMap=TWRCAS\ext_cntrline_35
yes

2023-03-17 13:37 UTC, pinatacolada requested changes

2023-03-17 13:37 UTC, pinatacolada commented on LPPC/Plugins/topsky/TopSkyMaps.txt
> -COLOR:MAP_GREY
a cor `MAP_BLACK` e antes das coordenadas, por readability, senao e o unico mapa ou parte de um mapa em que a cor e definida depois da geometria do mapa

2023-03-17 14:38 UTC, becas22 commented on LPPC/Plugins/topsky/TopSkySettings.txt
> +Setup_LoadMap=TWRCAS\ext_cntrline_35
https://github.com/pinatacolada/topskylppc/pull/619/commits/d20f019ad183bb9422a7f66a4bf5043be47fb575

2023-03-17 14:47 UTC, becas22 commented on LPPC/Plugins/topsky/TopSkyMaps.txt
> -COLOR:MAP_GREY
https://github.com/pinatacolada/topskylppc/pull/619/commits/129dbceb5fffd6b57934ec3a8477974d397f0216

2023-03-17 17:22 UTC, pinatacolada approved these changes

2023-03-17 17:24 UTC, merged