Updates stand wingspan restrictions
pinatacolada/topskylppc pull request #629
Opened 2023-03-03 18:44 UTC by eusaylah

Updates stands 107, 147, 801, 802, 803, MIL Apron wingspan restrictions due to taxilane wingspan restrictions

2023-03-07 17:47 UTC, pinatacolada requested changes

2023-03-07 17:47 UTC, pinatacolada commented on LPPC/Plugins/GroundRadar/GRpluginStands.txt
> +WINGSPAN:48.0
suponho que isto vem do #625

2023-03-07 17:47 UTC, pinatacolada commented on LPPC/Plugins/GroundRadar/GRpluginStands.txt
> +WINGSPAN:48.0
#625

2023-03-07 17:47 UTC, pinatacolada commented on LPPC/Plugins/GroundRadar/GRpluginStands.txt
> +WINGSPAN:48.0
#625

2023-03-07 17:47 UTC, pinatacolada commented on LPPC/Plugins/GroundRadar/GRpluginStands.txt
> +WINGSPAN:48.0
#625

2023-03-07 17:47 UTC, pinatacolada commented on LPPC/Plugins/GroundRadar/GRpluginStands.txt
> +WINGSPAN:48.0
#625

2023-03-07 17:47 UTC, pinatacolada commented on LPPC/Plugins/GroundRadar/GRpluginStands.txt
> +WINGSPAN:51.0
```suggestion
WINGSPAN:65.0
```

o 64 vinha de uma marca de chão com esse valor, que aparentemente agora até aumentou para 65

![image](https://user-images.githubusercontent.com/13833056/223505490-0f6c280a-384e-4942-94b1-3feb1e38aedf.png)


se aplicar-mos a restrição do W1 deixa-se de assignar C17 e até 747 militares e de estado na placa militar, quando é para isso que ela serve. No real o acesso é feito com o apoio de follow me, na vatsim temos que dar a abébia, mas é um caso particular e único 

https://youtube.com/live/pAjHlVq3Cz4?si=EnSIkaIECMiOmarE&t=1711

dito isto, provavelmente até nem seria má ideia de explicar este promaior no sop....

2023-03-17 13:41 UTC, pinatacolada requested changes
falta corrigir os outros wingspans da historia do 767

2023-03-18 10:56 UTC, eusaylah commented
Como assim? Não percebi o que falta

2023-03-18 11:34 UTC, pinatacolada commented
nos outros stands da review ainda estas a tentar mudar o wingspan para o do 763 sem winglets

2023-03-18 11:53 UTC, eusaylah commented
o que eu fiz foi reduzir o wingspan desses stands por causa das taxiways que os aviões têm de passar para lá chegar. Por exemplo, para chegar aos stds 801, 802 e 803, têm de passar na W1 que tem uma restrição de 48 m. Isto evita recebermos o TWY TYPE quando estamos a mandar um avião para o seu stand.

2023-03-18 12:02 UTC, pinatacolada commented
eu sei, mas W1 sao 51m
https://github.com/pinatacolada/topskylppc/blob/cd094ac66b9b7d925fcc70234bf6786030a0424f/LPPC/Plugins/GroundRadar/GRpluginMaps.txt#L10601-L10607

2023-03-18 12:02 UTC, pinatacolada commented on LPPC/Plugins/GroundRadar/GRpluginStands.txt
> +WINGSPAN:48.0
https://github.com/pinatacolada/topskylppc/blob/cd094ac66b9b7d925fcc70234bf6786030a0424f/LPPC/Plugins/GroundRadar/GRpluginMaps.txt#L10601-L10607

2023-03-18 12:10 UTC, eusaylah commented
my bad, pensava que era 48. vou corrigir

2023-03-18 12:34 UTC, pinatacolada approved these changes

2023-03-18 12:35 UTC, merged